CREATE DATABASE CartTest;

USE CartTest;

CREATE TABLE "Cart"
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CustomerID INT NOT NULL	
);

CREATE TABLE "Order"
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	OrderName VARCHAR(30),
	TotalPrice MONEY,
	CartID INT FOREIGN KEY REFERENCES Cart("ID")	
);

CREATE TABLE "OrderItem"
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	OrderID INT FOREIGN KEY REFERENCES "Order"("ID"),
	Name VARCHAR(30)		
);

CREATE TABLE "Customer"
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CartID INT FOREIGN KEY REFERENCES "Cart"("ID"),
	Name VARCHAR(30)		
);

